version: '3.8'

services:

  # --------------------------REPLICACION-------------------------------------------------


  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks:
      - mysql-network
      - app-network
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=testdb

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks:
      - mysql-network
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=testdb

  phpmyadmin1:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    environment:
      PMA_HOST: mysql-master
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - mysql-network
    ports:
      - "8081:80"

  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
      PMA_HOST: mysql-slave
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - mysql-network
    ports:
      - "8082:80"


  # --------------------------FIN REPLICACION-------------------------------------------------

  aplicacionpython2_1:  # Instancia 1 de la app
    container_name: aplicacionpython2_1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=testdb
      - MYSQL_PORT=3306
    networks:
      - app-network

  aplicacionpython2_2:  # Instancia 2 de la app
    container_name: aplicacionpython2_2
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=testdb
      - MYSQL_PORT=3306
    networks:
      - app-network
  
  aplicacionpython2_3:  # Instancia 3 de la app
    container_name: aplicacionpython2_3
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql-slave
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=testdb
      - MYSQL_PORT=3306
    networks:
      - app-network

  nginx_22:
    image: nginx:latest
    container_name: nginx_22
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - aplicacionpython2_1
      - aplicacionpython2_2
      - aplicacionpython2_3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


networks:
  mysql-network:
    driver: bridge
  app-network:
    driver: bridge
